[supabase]
url = "https://cnuyusxtrxzijaxippdx.supabase.co"
key = "sb_publishable_lsIZbboZ9lDpZWB1mdH46Q_Itqc5G6_"  <-- Make sure this is the NEW key you just generated!

[general]
admin_password = "8522"